#Checks to see if victim is staff
execute @s[scores={stafftag=1}] ~~~ tellraw @a {"rawtext":[{"text":"§¶§cAtomic §¶§b→ §bUnable to use smite on §d"},{"selector":"@s"},{"text":" §¶§bbecause they are staff."}]}

#Smite players
execute @s[scores={stafftag=0}] ~~~ tellraw @a {"rawtext":[{"text":"§¶§cAtomic §¶§b→ §d"},{"selector":"@s"},{"text":" §¶§bwas smited by a operator"}]}
execute @s[scores={stafftag=0}] ~~3~ summon lightning_bolt
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-1 ~1 ~1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~1 ~1 ~-1
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~1 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~1 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~-2 ~2 ~2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~2 ~2 ~-2
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~
execute @s[scores={stafftag=0}] ~~~ particle minecraft:totem_particle ~ ~1 ~

execute @s[scores={stafftag=0}] ~~~ kill @s
