replaceitem entity @s[scores={stafftag=0}] slot.hotbar 0 air
replaceitem entity @s[scores={stafftag=0}] slot.hotbar 1 air
replaceitem entity @s[scores={stafftag=0}] slot.hotbar 2 air
replaceitem entity @s[scores={stafftag=0}] slot.hotbar 3 air
replaceitem entity @s[scores={stafftag=0}] slot.hotbar 4 air
replaceitem entity @s[scores={stafftag=0}] slot.hotbar 5 air
replaceitem entity @s[scores={stafftag=0}] slot.hotbar 6 air
replaceitem entity @s[scores={stafftag=0}] slot.hotbar 7 air
replaceitem entity @s[scores={stafftag=0}] slot.hotbar 8 air
