#Spawn EGGS
clear @a[scores={ownertag=0}] spawn_egg
clear @a[scores={ownertag=0}] monster_egg
clear @a[scores={ownertag=0}] axolotl_spawn_egg
clear @a[scores={ownertag=0}] bat_spawn_egg
clear @a[scores={ownertag=0}] bee_spawn_egg
clear @a[scores={ownertag=0}] blaze_spawn_egg
clear @a[scores={ownertag=0}] cat_spawn_egg
clear @a[scores={ownertag=0}] cave_spider_spawn_egg
clear @a[scores={ownertag=0}] chicken_spawn_egg
clear @a[scores={ownertag=0}] cod_spawn_egg
clear @a[scores={ownertag=0}] cow_spawn_egg
clear @a[scores={ownertag=0}] creeper_spawn_egg
clear @a[scores={ownertag=0}] dolphin_spawn_egg
clear @a[scores={ownertag=0}] donkey_spawn_egg
clear @a[scores={ownertag=0}] drowned_spawn_egg
clear @a[scores={ownertag=0}] elder_guardian_spawn_egg
clear @a[scores={ownertag=0}] enderman_spawn_egg
clear @a[scores={ownertag=0}] endermite_spawn_egg
clear @a[scores={ownertag=0}] evoker_spawn_egg
clear @a[scores={ownertag=0}] fox_spawn_egg
clear @a[scores={ownertag=0}] ghast_spawn_egg
clear @a[scores={ownertag=0}] guardian_spawn_egg
clear @a[scores={ownertag=0}] hoglin_spawn_egg
clear @a[scores={ownertag=0}] horse_spawn_egg
clear @a[scores={ownertag=0}] husk_spawn_egg
clear @a[scores={ownertag=0}] llama_spawn_egg
clear @a[scores={ownertag=0}] magma_cube_spawn_egg
clear @a[scores={ownertag=0}] mooshroom_spawn_egg
clear @a[scores={ownertag=0}] mule_spawn_egg
clear @a[scores={ownertag=0}] npc_spawn_egg
clear @a[scores={ownertag=0}] ocelot_spawn_egg
clear @a[scores={ownertag=0}] panda_spawn_egg
clear @a[scores={ownertag=0}] parrot_spawn_egg
clear @a[scores={ownertag=0}] phantom_spawn_egg
clear @a[scores={ownertag=0}] pig_spawn_egg
clear @a[scores={ownertag=0}] piglin_brute_spawn_egg
clear @a[scores={ownertag=0}] piglin_spawn_egg
clear @a[scores={ownertag=0}] pillager_spawn_egg
clear @a[scores={ownertag=0}] polar_bear_spawn_egg
clear @a[scores={ownertag=0}] pufferfish_spawn_egg
clear @a[scores={ownertag=0}] rabbit_spawn_egg
clear @a[scores={ownertag=0}] ravager_spawn_egg
clear @a[scores={ownertag=0}] salmon_spawn_egg
clear @a[scores={ownertag=0}] sheep_spawn_egg
clear @a[scores={ownertag=0}] shulker_spawn_egg
clear @a[scores={ownertag=0}] silverfish_spawn_egg
clear @a[scores={ownertag=0}] skeleton_horse_spawn_egg
clear @a[scores={ownertag=0}] skeleton_spawn_egg
clear @a[scores={ownertag=0}] slime_spawn_egg
clear @a[scores={ownertag=0}] spider_spawn_egg
clear @a[scores={ownertag=0}] squid_spawn_egg
clear @a[scores={ownertag=0}] stray_spawn_egg
clear @a[scores={ownertag=0}] strider_spawn_egg
clear @a[scores={ownertag=0}] tropical_fish_spawn_egg
clear @a[scores={ownertag=0}] turtle_spawn_egg
clear @a[scores={ownertag=0}] vex_spawn_egg
clear @a[scores={ownertag=0}] vindicator_spawn_egg
clear @a[scores={ownertag=0}] villager_spawn_egg
clear @a[scores={ownertag=0}] wandering_trader_spawn_egg
clear @a[scores={ownertag=0}] witch_spawn_egg
clear @a[scores={ownertag=0}] wither_skeleton_spawn_egg
clear @a[scores={ownertag=0}] wolf_spawn_egg
clear @a[scores={ownertag=0}] zoglin_spawn_egg
clear @a[scores={ownertag=0}] zombie_horse_spawn_egg
clear @a[scores={ownertag=0}] zombie_pigman_spawn_egg
clear @a[scores={ownertag=0}] zombie_spawn_egg
clear @a[scores={ownertag=0}] zombie_villager_spawn_egg
clear @a[scores={ownertag=0}] glow_squid_spawn_egg
clear @a[scores={ownertag=0}] goat_spawn_egg

#This hides this from the in-game function command directory
execute @f ~~~ hide
tag @f[tag=""] add hide
